version: "3"

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql
    networks:
      - postgres-compose-network

  rabbitMq:
    container_name: service-rabbitmq
    image: rabbitmq:3.9.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "45806:15672"
    restart: always
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - rabbitmq-service-net

networks:
  postgres-compose-network:
    driver: bridge
  rabbitmq-service-net: { }